name: personal_tracker
description: "Personal tracking app with offline support and dark mode."

publish_to: 'none' 

version: 1.0.0+1

environment: 
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  intl: ^0.20.2
  sqflite: ^2.4.2
  path: ^1.9.1
  connectivity_plus: ^6.1.4
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  google_maps_flutter_web: ^0.5.12+2
  device_info_plus: ^11.5.0
  image_picker: ^1.1.2
  camera: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

 
